### ISSUE TITLE
Can you provide the full 3d design file?

### ISSUE THREAD

**Issue by pepijndik** [hannu-hell/Mechanical_Thing-Addams-Family-#1]
First of all what an awesome project! 
For school, we are working on exactly the same and thought let's use your instructables as an example ;-) Now we are facing a small issue. We wanted to reuse your design and alter it a bit. But because those are STL files we can't modify them.  en because converting them into a mesh didn't work. so  I thought maybe you could share the cad files instead of the. stl files  

Kind regards!

**Comment by hanoonmalik** [comment]
Hi pepjin,

Glad that you liked my project and its of use to your studies. I’ll figure out a way to embed the design in the instructable so that u will be able to open it in fusion360.

Sorry for the late reply.
Kind regards,
Hannu
Sent from my iPhone

On 08-05-2024, at 21:59, pepijn ***@***.***> wrote:

﻿

First of all what an awesome project!
For school, we are working on exactly the same and thought let's use your instructables as an example ;-) Now we are facing a small issue. We wanted to reuse your design and alter it a bit. But because those are STL files we can't modify them. en because converting them into a mesh didn't work. so I thought maybe you could share the cad files instead of the. stl files

Kind regards!

**Comment by pepijndik** [comment]
Thx would be nice, if you only could share them through github also fine😃.

Kind regards

**Comment by hanoonmalik** [comment]
Hi Pepjin,
I am unable to share the fusion360 file here since its not supported here. Provide me your email and Ill be able to attach the file and send it to you.

Kind Regards

**Comment by hanoonmalik** [comment]
Oh nevermind,
I've uploaded the file to the repository. Hope it helps.
